spring:
  application:
    name: workshop
  datasource:
    url: jdbc:mysql://localhost:3306/pokemon_world
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8888

